"""
Django admin configuration generator using CodeBuilder.

Generates admin.py with ModelAdmin classes for all models.
"""

import logging

from ..code_builder import PythonCodeBuilder
from ..schema import DatabaseSchema, TableSchema, FieldType

logger = logging.getLogger(__name__)


class AdminGenerator:
    """Generates Django admin.py file content."""

    def __init__(self, schema: DatabaseSchema):
        self.schema = schema

    def generate(self) -> str:
        """Generate the complete admin.py file."""
        b = PythonCodeBuilder()

        # Get non-through tables with primary keys
        tables = [t for t in self.schema.get_non_through_tables() if t.primary_key_columns]

        model_names = [t.model_name for t in tables]

        # Docstring
        b.docstring("Django admin configuration.\n\nGenerated by drf-auto-generator.")
        b.line()

        # Imports
        b.import_("django.contrib", ["admin"])
        if model_names:
            b.import_(".models", model_names)
        b.line()
        b.line()

        # Generate admin classes
        for table in tables:
            self._generate_admin_class(b, table)
            b.line()
            b.line()

        return b.build()

    def _generate_admin_class(self, b: PythonCodeBuilder, table: TableSchema) -> None:
        """Generate a ModelAdmin class and registration."""
        model_name = table.model_name
        admin_name = f"{model_name}Admin"

        # Get field configurations
        list_display = self._get_list_display(table)
        list_filter = self._get_list_filter(table)
        search_fields = self._get_search_fields(table)

        # Decorator to register
        with b.class_(admin_name, bases=["admin.ModelAdmin"], decorators=[f"admin.register({model_name})"]):
            # Docstring
            b.docstring(f"Admin configuration for {model_name}.")
            b.line()

            # list_display
            if list_display:
                fields_str = ", ".join(f'"{f}"' for f in list_display)
                b.line(f"list_display = [{fields_str}]")

            # list_filter
            if list_filter:
                fields_str = ", ".join(f'"{f}"' for f in list_filter)
                b.line(f"list_filter = [{fields_str}]")

            # search_fields
            if search_fields:
                fields_str = ", ".join(f'"{f}"' for f in search_fields)
                b.line(f"search_fields = [{fields_str}]")

            # ordering
            pk_field = self._get_pk_field(table)
            b.line(f'ordering = ["{pk_field}"]')

            # If no customizations, add pass
            if not list_display and not list_filter and not search_fields:
                b.pass_()

    def _get_list_display(self, table: TableSchema, limit: int = 6) -> list[str]:
        """Get fields for list_display."""
        fields = []

        # Add PK first
        pk_field = self._get_pk_field(table)
        fields.append(pk_field)

        # Add displayable fields
        displayable_types = {
            FieldType.CHAR, FieldType.TEXT, FieldType.EMAIL,
            FieldType.INTEGER, FieldType.BIG_INTEGER,
            FieldType.DATE, FieldType.DATETIME, FieldType.BOOLEAN
        }

        for col in table.columns:
            if col.field_type in displayable_types:
                field_name = col.django_field_name
                if field_name not in fields:
                    # Skip FK columns
                    is_handled = any(
                        rel.source_column == col.name
                        for rel in table.relationships
                    )
                    if not is_handled:
                        fields.append(field_name)

        return fields[:limit]

    def _get_list_filter(self, table: TableSchema, limit: int = 4) -> list[str]:
        """Get fields for list_filter."""
        fields = []

        # Add FK relationships
        for rel in table.relationships:
            if rel.type.value == "many-to-one":
                fields.append(rel.name)

        # Add boolean and choice fields
        for col in table.columns:
            if col.field_type == FieldType.BOOLEAN:
                fields.append(col.django_field_name)
            elif col.choices:
                fields.append(col.django_field_name)

        return fields[:limit]

    def _get_search_fields(self, table: TableSchema, limit: int = 4) -> list[str]:
        """Get fields for search_fields."""
        searchable_types = {FieldType.CHAR, FieldType.TEXT, FieldType.EMAIL}
        fields = []

        for col in table.columns:
            if col.field_type in searchable_types:
                # Skip FK columns
                is_handled = any(
                    rel.source_column == col.name
                    for rel in table.relationships
                )
                if not is_handled:
                    fields.append(col.django_field_name)

        return fields[:limit]

    def _get_pk_field(self, table: TableSchema) -> str:
        """Get the primary key field name."""
        if table.has_composite_pk:
            return "pk"

        if table.pk_column:
            col = table.get_column(table.pk_column)
            if col:
                return col.django_field_name

        return "pk"
