"""
Django project files generator using CodeBuilder.

Generates settings.py, manage.py, wsgi.py, asgi.py, and other project files.
"""

import logging
from typing import Any, Optional

from ..code_builder import PythonCodeBuilder
from ..schema import DatabaseSchema

logger = logging.getLogger(__name__)


class ProjectFilesGenerator:
    """Generates Django project configuration files."""

    def __init__(self, schema: DatabaseSchema, config: Optional[dict[str, Any]] = None):
        self.schema = schema
        self.config = config or {}

    def generate_all(self) -> dict[str, str]:
        """Generate all project files."""
        project_name = self.schema.project_name
        app_name = self.schema.app_name

        return {
            f"{project_name}/__init__.py": "",
            f"{project_name}/settings.py": self.generate_settings(),
            f"{project_name}/urls.py": self.generate_project_urls(),
            f"{project_name}/wsgi.py": self.generate_wsgi(),
            f"{project_name}/asgi.py": self.generate_asgi(),
            f"{app_name}/__init__.py": "",
            f"{app_name}/apps.py": self.generate_apps(),
            "manage.py": self.generate_manage(),
            "requirements.txt": self.generate_requirements(),
            ".env.example": self.generate_env_example(),
        }

    def generate_settings(self) -> str:
        """Generate settings.py."""
        b = PythonCodeBuilder()
        project_name = self.schema.project_name
        app_name = self.schema.app_name
        db_name = self.config.get("database_name", "postgres")

        # Docstring
        b.docstring(f"Django settings for {project_name} project.\n\nGenerated by drf-auto-generator.")
        b.line()

        # Imports
        b.import_("pathlib", ["Path"])
        b.import_("os")
        b.line()

        # Try to import dotenv
        with b.try_():
            b.import_("dotenv")
            b.line("dotenv.load_dotenv()")
        with b.except_("ImportError"):
            b.pass_()
        b.line()

        # BASE_DIR
        b.line("BASE_DIR = Path(__file__).resolve().parent.parent")
        b.line()

        # Security settings
        b.comment("SECURITY WARNING: keep the secret key used in production secret!")
        b.line('SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-change-me-in-production")')
        b.line()

        b.comment("SECURITY WARNING: don't run with debug turned on in production!")
        b.line('DEBUG = os.environ.get("DEBUG", "True").lower() == "true"')
        b.line()

        b.line('ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "*").split(",")')
        b.line()

        # Installed apps
        b.line("INSTALLED_APPS = [")
        b.indent()
        b.comment("Django apps")
        b.line('"django.contrib.admin",')
        b.line('"django.contrib.auth",')
        b.line('"django.contrib.contenttypes",')
        b.line('"django.contrib.sessions",')
        b.line('"django.contrib.messages",')
        b.line('"django.contrib.staticfiles",')
        b.line()
        b.comment("Third-party apps")
        b.line('"rest_framework",')
        b.line('"django_filters",')
        b.line('"corsheaders",')
        b.line('"drf_spectacular",')
        b.line()
        b.comment("Local apps")
        b.line(f'"{app_name}",')
        b.dedent()
        b.line("]")
        b.line()

        # Middleware
        b.line("MIDDLEWARE = [")
        b.indent()
        b.line('"django.middleware.security.SecurityMiddleware",')
        b.line('"corsheaders.middleware.CorsMiddleware",')
        b.line('"django.contrib.sessions.middleware.SessionMiddleware",')
        b.line('"django.middleware.common.CommonMiddleware",')
        b.line('"django.middleware.csrf.CsrfViewMiddleware",')
        b.line('"django.contrib.auth.middleware.AuthenticationMiddleware",')
        b.line('"django.contrib.messages.middleware.MessageMiddleware",')
        b.line('"django.middleware.clickjacking.XFrameOptionsMiddleware",')
        b.dedent()
        b.line("]")
        b.line()

        # Root URL conf
        b.line(f'ROOT_URLCONF = "{project_name}.urls"')
        b.line()

        # Templates
        b.line("TEMPLATES = [")
        b.indent()
        b.line("{")
        b.indent()
        b.line('"BACKEND": "django.template.backends.django.DjangoTemplates",')
        b.line('"DIRS": [],')
        b.line('"APP_DIRS": True,')
        b.line('"OPTIONS": {')
        b.indent()
        b.line('"context_processors": [')
        b.indent()
        b.line('"django.template.context_processors.debug",')
        b.line('"django.template.context_processors.request",')
        b.line('"django.contrib.auth.context_processors.auth",')
        b.line('"django.contrib.messages.context_processors.messages",')
        b.dedent()
        b.line("],")
        b.dedent()
        b.line("},")
        b.dedent()
        b.line("},")
        b.dedent()
        b.line("]")
        b.line()

        # WSGI
        b.line(f'WSGI_APPLICATION = "{project_name}.wsgi.application"')
        b.line()

        # Database
        b.comment("Database")
        b.line("DATABASES = {")
        b.indent()
        b.line('"default": {')
        b.indent()
        b.line('"ENGINE": "django.db.backends.postgresql",')
        b.line(f'"NAME": os.environ.get("DB_NAME", "{db_name}"),')
        b.line('"USER": os.environ.get("DB_USER", "postgres"),')
        b.line('"PASSWORD": os.environ.get("DB_PASSWORD", ""),')
        b.line('"HOST": os.environ.get("DB_HOST", "localhost"),')
        b.line('"PORT": os.environ.get("DB_PORT", "5432"),')
        b.dedent()
        b.line("}")
        b.dedent()
        b.line("}")
        b.line()

        # Password validators
        b.line("AUTH_PASSWORD_VALIDATORS = [")
        b.indent()
        b.line('{"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},')
        b.line('{"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},')
        b.line('{"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},')
        b.line('{"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},')
        b.dedent()
        b.line("]")
        b.line()

        # Internationalization
        b.line('LANGUAGE_CODE = "en-us"')
        b.line('TIME_ZONE = "UTC"')
        b.line("USE_I18N = True")
        b.line("USE_TZ = True")
        b.line()

        # Static files
        b.line('STATIC_URL = "static/"')
        b.line()

        # Default primary key field type
        b.line('DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"')
        b.line()

        # REST Framework settings
        b.line("REST_FRAMEWORK = {")
        b.indent()
        b.line('"DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",')
        b.line('"DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",')
        b.line('"PAGE_SIZE": 20,')
        b.line('"DEFAULT_FILTER_BACKENDS": [')
        b.indent()
        b.line('"django_filters.rest_framework.DjangoFilterBackend",')
        b.line('"rest_framework.filters.SearchFilter",')
        b.line('"rest_framework.filters.OrderingFilter",')
        b.dedent()
        b.line("],")
        b.dedent()
        b.line("}")
        b.line()

        # DRF Spectacular settings
        b.line("SPECTACULAR_SETTINGS = {")
        b.indent()
        b.line(f'"TITLE": "{project_name} API",')
        b.line('"DESCRIPTION": "Auto-generated REST API",')
        b.line('"VERSION": "1.0.0",')
        b.line('"SERVE_INCLUDE_SCHEMA": False,')
        b.dedent()
        b.line("}")
        b.line()

        # CORS settings
        b.line("CORS_ALLOW_ALL_ORIGINS = DEBUG")

        return b.build()

    def generate_project_urls(self) -> str:
        """Generate project-level urls.py."""
        b = PythonCodeBuilder()
        project_name = self.schema.project_name
        app_name = self.schema.app_name

        b.docstring(f"URL configuration for {project_name} project.")
        b.line()

        b.import_("django.contrib", ["admin"])
        b.import_("django.urls", ["path", "include"])
        b.import_("drf_spectacular.views", ["SpectacularAPIView", "SpectacularSwaggerView", "SpectacularRedocView"])
        b.line()
        b.line()

        b.line("urlpatterns = [")
        b.indent()
        b.comment("Admin")
        b.line('path("admin/", admin.site.urls),')
        b.line()
        b.comment("API endpoints")
        b.line(f'path("api/", include("{app_name}.urls")),')
        b.line()
        b.comment("OpenAPI schema")
        b.line('path("api/schema/", SpectacularAPIView.as_view(), name="schema"),')
        b.line('path("api/schema/swagger-ui/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger-ui"),')
        b.line('path("api/schema/redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),')
        b.dedent()
        b.line("]")

        return b.build()

    def generate_wsgi(self) -> str:
        """Generate wsgi.py."""
        b = PythonCodeBuilder()
        project_name = self.schema.project_name

        b.docstring(f"WSGI config for {project_name} project.")
        b.line()

        b.import_("os")
        b.import_("django.core.wsgi", ["get_wsgi_application"])
        b.line()
        b.line()

        b.line(f'os.environ.setdefault("DJANGO_SETTINGS_MODULE", "{project_name}.settings")')
        b.line()
        b.line("application = get_wsgi_application()")

        return b.build()

    def generate_asgi(self) -> str:
        """Generate asgi.py."""
        b = PythonCodeBuilder()
        project_name = self.schema.project_name

        b.docstring(f"ASGI config for {project_name} project.")
        b.line()

        b.import_("os")
        b.import_("django.core.asgi", ["get_asgi_application"])
        b.line()
        b.line()

        b.line(f'os.environ.setdefault("DJANGO_SETTINGS_MODULE", "{project_name}.settings")')
        b.line()
        b.line("application = get_asgi_application()")

        return b.build()

    def generate_apps(self) -> str:
        """Generate apps.py for the app."""
        b = PythonCodeBuilder()
        app_name = self.schema.app_name

        b.import_("django.apps", ["AppConfig"])
        b.line()
        b.line()

        # Convert app_name to PascalCase for class name
        class_name = "".join(word.capitalize() for word in app_name.split("_")) + "Config"

        with b.class_(class_name, bases=["AppConfig"]):
            b.line('default_auto_field = "django.db.models.BigAutoField"')
            b.line(f'name = "{app_name}"')

        return b.build()

    def generate_manage(self) -> str:
        """Generate manage.py."""
        b = PythonCodeBuilder()
        project_name = self.schema.project_name

        b.line("#!/usr/bin/env python")
        b.docstring("Django's command-line utility for administrative tasks.")
        b.line()

        b.import_("os")
        b.import_("sys")
        b.line()
        b.line()

        with b.function("main"):
            b.docstring("Run administrative tasks.")
            b.line(f'os.environ.setdefault("DJANGO_SETTINGS_MODULE", "{project_name}.settings")')
            with b.try_():
                b.import_("django.core.management", ["execute_from_command_line"])
            with b.except_("ImportError", as_var="exc"):
                b.line("raise ImportError(")
                b.indent()
                b.line('"Couldn\'t import Django. Are you sure it\'s installed?"')
                b.dedent()
                b.line(") from exc")
            b.line("execute_from_command_line(sys.argv)")

        b.line()
        b.line()

        with b.if_('__name__ == "__main__"'):
            b.line("main()")

        return b.build()

    def generate_requirements(self) -> str:
        """Generate requirements.txt."""
        requirements = [
            "django>=5.0",
            "djangorestframework>=3.14",
            "django-filter>=23.0",
            "django-cors-headers>=4.0",
            "drf-spectacular>=0.26",
            "psycopg2-binary>=2.9",
            "python-dotenv>=1.0",
            "black>=23.0",  # For code formatting
        ]
        return "\n".join(requirements) + "\n"

    def generate_env_example(self) -> str:
        """Generate .env.example file."""
        db_name = self.config.get("database_name", "postgres")
        return f"""# Django settings
SECRET_KEY=your-secret-key-here
DEBUG=True
ALLOWED_HOSTS=localhost,127.0.0.1

# Database settings
DB_NAME={db_name}
DB_USER=postgres
DB_PASSWORD=your-password
DB_HOST=localhost
DB_PORT=5432
"""
