"""
Django URL configuration generator using CodeBuilder.

Generates URL patterns with DRF router configuration.
"""

import logging
import inflect

from ..code_builder import PythonCodeBuilder
from ..schema import DatabaseSchema

logger = logging.getLogger(__name__)

_inflect_engine = inflect.engine()


class UrlsGenerator:
    """Generates Django urls.py file content."""

    def __init__(self, schema: DatabaseSchema):
        self.schema = schema

    def generate(self) -> str:
        """Generate the complete urls.py file."""
        b = PythonCodeBuilder()

        # Get non-through tables with primary keys
        tables = [t for t in self.schema.get_non_through_tables() if t.primary_key_columns]

        viewset_names = [f"{t.model_name}ViewSet" for t in tables]

        # Docstring
        b.docstring("URL configuration for the API.\n\nGenerated by drf-auto-generator.")
        b.line()

        # Imports
        b.import_("django.urls", ["path", "include"])
        b.import_("rest_framework.routers", ["DefaultRouter"])
        if viewset_names:
            b.import_(".views", viewset_names)
        b.line()
        b.line()

        # Create router
        b.comment("Create a router and register viewsets")
        b.line("router = DefaultRouter()")
        b.line()

        # Register viewsets
        for table in tables:
            viewset_name = f"{table.model_name}ViewSet"
            # Use plural lowercase for URL path
            url_path = self._get_url_path(table.name)
            b.line(f'router.register(r"{url_path}", {viewset_name}, basename="{url_path}")')

        b.line()
        b.line()

        # URL patterns
        b.line("urlpatterns = [")
        b.indent()
        b.line('path("", include(router.urls)),')
        b.dedent()
        b.line("]")

        return b.build()

    def _get_url_path(self, table_name: str) -> str:
        """Get the URL path for a table (pluralized, lowercase, hyphenated)."""
        # Convert underscores to hyphens for URLs
        path = table_name.lower().replace("_", "-")
        # Ensure it's plural
        plural = _inflect_engine.plural(path)
        return plural if plural else path
