"""
Django REST Framework views generator using CodeBuilder.

Generates DRF ViewSet classes from the database schema IR.
"""

import logging
from typing import Any

from ..code_builder import PythonCodeBuilder
from ..schema import DatabaseSchema, TableSchema, RelationshipType, FieldType

logger = logging.getLogger(__name__)


class ViewsGenerator:
    """Generates Django REST Framework views.py file content."""

    def __init__(self, schema: DatabaseSchema):
        self.schema = schema

    def generate(self) -> str:
        """Generate the complete views.py file."""
        b = PythonCodeBuilder()

        # Get non-through tables
        tables = self.schema.get_non_through_tables()
        tables_with_pk = [t for t in tables if t.primary_key_columns]

        model_names = [t.model_name for t in tables_with_pk]
        serializer_names = [f"{t.model_name}Serializer" for t in tables_with_pk]

        # File docstring
        b.docstring("Generated by drf-auto-generator.\nDefines ViewSets for handling API requests.")
        b.line()

        # Imports
        b.import_("rest_framework", ["viewsets", "permissions", "filters"])
        b.import_("django_filters.rest_framework", ["DjangoFilterBackend"])
        if model_names:
            b.import_(".models", model_names)
        if serializer_names:
            b.import_(".serializers", serializer_names)
        b.line()
        b.line()

        # Generate viewset classes
        for table in tables_with_pk:
            self._generate_viewset_class(b, table)
            b.line()
            b.line()

        return b.build()

    def _generate_viewset_class(self, b: PythonCodeBuilder, table: TableSchema) -> None:
        """Generate a single ViewSet class."""
        model_name = table.model_name
        viewset_name = f"{model_name}ViewSet"
        serializer_name = f"{model_name}Serializer"

        # Get configuration
        search_fields = self._get_search_fields(table)
        ordering_fields = self._get_ordering_fields(table)
        filterset_fields = self._get_filterset_fields(table)
        pk_field = self._get_pk_field(table)

        with b.class_(viewset_name, bases=["viewsets.ModelViewSet"]):
            # Docstring
            b.docstring(f"API endpoint for {model_name}.\n\nProvides standard CRUD operations with filtering, search, and pagination.")
            b.line()

            # Queryset
            b.line(f"queryset = {model_name}.objects.all().order_by('{pk_field}')")

            # Serializer class
            b.line(f"serializer_class = {serializer_name}")
            b.line()

            # Permission classes
            b.line("permission_classes = [permissions.IsAuthenticatedOrReadOnly]")
            b.line()

            # Filter backends
            b.line("filter_backends = [")
            b.indent()
            b.line("filters.OrderingFilter,")
            b.line("filters.SearchFilter,")
            b.line("DjangoFilterBackend,")
            b.dedent()
            b.line("]")
            b.line()

            # Ordering fields
            if ordering_fields:
                fields_str = ", ".join(f'"{f}"' for f in ordering_fields)
                b.line(f"ordering_fields = [{fields_str}]")
            else:
                b.line(f'ordering_fields = ["{pk_field}"]')

            # Search fields
            if search_fields:
                fields_str = ", ".join(f'"{f}"' for f in search_fields)
                b.line(f"search_fields = [{fields_str}]")
            else:
                b.line("search_fields = []")

            # Filterset fields
            if filterset_fields:
                b.line("filterset_fields = {")
                b.indent()
                for field, lookups in filterset_fields.items():
                    lookups_str = ", ".join(f'"{l}"' for l in lookups)
                    b.line(f'"{field}": [{lookups_str}],')
                b.dedent()
                b.line("}")

    def _get_search_fields(self, table: TableSchema, limit: int = 5) -> list[str]:
        """Get fields suitable for search."""
        searchable_types = {FieldType.CHAR, FieldType.TEXT, FieldType.EMAIL}
        fields = []

        for col in table.columns:
            if col.field_type in searchable_types:
                # Skip fields handled by relationships
                is_handled = any(
                    rel.source_column == col.name
                    for rel in table.relationships
                )
                if not is_handled:
                    fields.append(col.django_field_name)

        return fields[:limit]

    def _get_ordering_fields(self, table: TableSchema, limit: int = 5) -> list[str]:
        """Get fields suitable for ordering."""
        pk_field = self._get_pk_field(table)
        fields = [pk_field]

        orderable_types = {
            FieldType.CHAR, FieldType.TEXT, FieldType.EMAIL,
            FieldType.DATE, FieldType.DATETIME
        }

        for col in table.columns:
            if col.field_type in orderable_types:
                field_name = col.django_field_name
                if field_name != pk_field:
                    # Skip fields handled by relationships
                    is_handled = any(
                        rel.source_column == col.name
                        for rel in table.relationships
                    )
                    if not is_handled:
                        fields.append(field_name)

        return fields[:limit]

    def _get_filterset_fields(self, table: TableSchema) -> dict[str, list[str]]:
        """Get fields configuration for django-filter."""
        filterset_fields: dict[str, list[str]] = {}

        # Add FK relationships
        for rel in table.relationships:
            if rel.type == RelationshipType.MANY_TO_ONE:
                filterset_fields[rel.name] = ["exact"]

        # Add indexed fields
        for idx in table.indexes:
            for field_name in idx.fields:
                if field_name not in filterset_fields:
                    col = table.get_column(field_name)
                    if col:
                        lookups = self._get_lookups_for_type(col.field_type)
                        filterset_fields[col.django_field_name] = lookups

        # Add unique fields
        for col in table.columns:
            if col.unique and not col.primary_key:
                field_name = col.django_field_name
                if field_name not in filterset_fields:
                    filterset_fields[field_name] = ["exact"]

        return filterset_fields

    def _get_lookups_for_type(self, field_type: FieldType) -> list[str]:
        """Get appropriate filter lookups for a field type."""
        text_types = {FieldType.CHAR, FieldType.TEXT, FieldType.EMAIL, FieldType.URL}
        numeric_types = {
            FieldType.INTEGER, FieldType.BIG_INTEGER, FieldType.SMALL_INTEGER,
            FieldType.POSITIVE_INTEGER, FieldType.FLOAT, FieldType.DECIMAL
        }
        date_types = {FieldType.DATE, FieldType.DATETIME}

        if field_type in text_types:
            return ["exact", "icontains"]
        elif field_type in numeric_types:
            return ["exact", "gte", "lte"]
        elif field_type in date_types:
            return ["exact", "gte", "lte"]
        elif field_type == FieldType.BOOLEAN:
            return ["exact"]
        else:
            return ["exact"]

    def _get_pk_field(self, table: TableSchema) -> str:
        """Get the primary key field name for ordering."""
        if table.has_composite_pk:
            if table.is_m2m_through_table:
                return "id"  # Django auto-generates id for through tables
            else:
                return "pk"  # CompositePrimaryKey uses pk

        if table.pk_column:
            col = table.get_column(table.pk_column)
            if col:
                return col.django_field_name

        return "pk"
